apiVersion: v1
kind: Service
metadata:
  name: dummy-post-office-vite-nginx-app-service
  namespace: dummy-post-office-namespace
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80 # Debe coincidir con el puerto expuesto por el contenedor
      protocol: TCP
  selector:
    app: dummy-post-office-vite-nginx-app # Asegúrate de que coincida con las etiquetas del pod
